version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BLANK # root 계정의 비밀번호 설정
      MYSQL_DATABASE: goodong
      MYSQL_USER: BLANK # 사용자 계정의 이름 설정
      MYSQL_PASSWORD: BLANK # 사용자 계정의 비밀번호 설정
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/goodong?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: BLANK # 사용자 계정의 이름 설정
      SPRING_DATASOURCE_PASSWORD: BLANK # 사용자 계정의 비밀번호 설정
      SERVER_PORT: 8000
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JWT_SECRET: BLANK # JWT 토큰의 비밀키 설정
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_SERVLET_MULTIPART_MAXFILESIZE: 100MB
      SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: 100MB
      MODEL_LOCATION: /uploads
      SPRING_ELASTIC_URL: BLANK # Elasticsearch 서버의 URL 설정
      SPRING_DATA_ELASTICSEARCH_REPOSITORIES_ENABLED: "true"
      SPRING_ELASTICSEARCH_URIS: BLANK # Elasticsearch 클러스터의 URI 설정

volumes:
  mysql_data:
